name: Linux_Node_Workflow_ScmCred

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: 'run npm'
      run: |
        npm install
      
    - uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: Test-Function-App-Rami
        publish-profile: ${{ secrets.SCM_CREDENTIALS }}
